name: instances-updater
on:
  schedule:
    - cron: '10 22 */1 * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: python main.py
      - run: |
          git config --local user.email "action@github.com" 
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update instances" -a || :
      - uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
